Controllers/ClientController.cs
using DreamDay.Business.Interface;
using DreamDay.Business.Service;
using DreamDay.Data;
using DreamDay.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DreamDay.Controllers
{
    [Authorize(Roles = "Client")]
    public class ClientController : Controller
    {
        private readonly IWeddingService _weddingService;
        private readonly IChecklistItemService _checklistItemService;
        private readonly IGuestService _guestService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ITimelineService _timelineService;

        public ClientController(
            IWeddingService weddingService, 
            SignInManager<ApplicationUser> signInManager,
            IChecklistItemService checklistItemService,
            IGuestService guestService,
            ITimelineService timelineService)
        {
            _signInManager = signInManager;
            _weddingService = weddingService;
            _checklistItemService = checklistItemService;
            _guestService = guestService;
            _timelineService = timelineService;
        }
        public IActionResult Dashboard()
        {
            var SignedInUser = _signInManager.UserManager.GetUserAsync(User).Result;
            var wedding = _weddingService.GetWeddingByClientId(SignedInUser?.Id);

            if (wedding != null)
            {
                HttpContext.Session.SetInt32("WeddingId", wedding.Id);
                wedding.ChecklistItems = _checklistItemService.GetChecklistItemsByWeddingId(wedding.Id);
                wedding.Guests = _guestService.GetGuestsByWeddingId(wedding.Id);
                wedding.Timelines = _timelineService.GetTimelinesByWeddingId(wedding.Id);
            }

            return View(wedding);
        }

        public IActionResult MarkAsDone(int itemId)
        {
            if (_checklistItemService.MarkAsDone(itemId))
            {
                return RedirectToAction("Dashboard");
            }
            return View();
        }

        public IActionResult MarkAsAttending(int itemId)
        {
            if (_guestService.MarkAsAttending(itemId))
            {
                return RedirectToAction("Dashboard");
            }
            return View();
        }

        public IActionResult MarkRimelineAsDone(int itemId)
        {
            if (_timelineService.MarkAsDone(itemId))
            {
                return RedirectToAction("Dashboard");
            }
            return View();
        }
    }
}

Controllers/GuestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DreamDay.Data;
using DreamDay.Models;
using Microsoft.AspNetCore.Authorization;
using DreamDay.Business.Interface;
using DreamDay.Business.Service;

namespace DreamDay.Controllers
{
    [Authorize(Roles = "Client")]
    public class GuestsController : Controller
    {
        private readonly IGuestService _guestService;

        public GuestsController(IGuestService guestService)
        {
            _guestService = guestService;
        }

        // GET: Guests
        public async Task<IActionResult> Index()
        {
            int _WeddingId = 0;
            var sessionWeddingId = HttpContext.Session.GetInt32("WeddingId");
            if (sessionWeddingId.HasValue)
            {
                _WeddingId = sessionWeddingId.Value;
            }
            else
            {
                _WeddingId = 0;
            }
            var guests = _guestService.GetGuestsByWeddingId(_WeddingId);
            return View(guests);
        }

        // GET: Guests/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var guest = _guestService.GetGuestById(id);
            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        // GET: Guests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Phone,MealPreference,TableNumber")] Guest guest)
        {
            ModelState.Remove("Wedding");
            if (ModelState.IsValid)
            {
                int? weddingId = HttpContext.Session.GetInt32("WeddingId");
                if (weddingId.HasValue)
                {
                    guest.WeddingId = weddingId.Value; // Set the WeddingId from session
                    guest.RSVP = false; // Default value for RSVP
                    _guestService.AddGuest(guest);
                    return RedirectToAction(nameof(Index), new { weddingId = weddingId });
                }
                else
                {
                    ModelState.AddModelError("", "Wedding ID is not set in session.");
                }
            }
            else
            {
                return View(guest);
            }
            return View(guest);
        }

        // GET: Guests/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var guest = _guestService.GetGuestById(id);
            if (guest == null)
            {
                return NotFound();
            }
            return View(guest);
        }

        // POST: Guests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Phone,RSVP,MealPreference,TableNumber")] Guest guest)
        {
            if (id != guest.Id)
            {
                return NotFound();
            }
            ModelState.Remove("Wedding");
            if (ModelState.IsValid)
            {
                int? weddingId = HttpContext.Session.GetInt32("WeddingId");
                if (weddingId.HasValue)
                {
                    guest.WeddingId = weddingId.Value; // Set the WeddingId from session
                    _guestService.UpdateGuest(guest);
                    return RedirectToAction(nameof(Index), new { weddingId = weddingId });
                }
                else
                {
                    ModelState.AddModelError("", "Wedding ID is not set in session.");
                }
            }
            else
            {
                return View(guest);
            }
            return View(guest);
        }

        // GET: Guests/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var guest = _guestService.GetGuestById(id);
            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        // POST: Guests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _guestService.DeleteGuest(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Client/Dashboard.cshtml
@{
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
    ViewData["Title"] = "Dashboard";
}
@model Wedding
<div class="container-fluid">
    <h1>Client Dashboard</h1>
    <div class="row">

        <div class="col-md-6">
            <div class="card table-card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-4">
                            <h3>Wedding ToDo List</h3>
                        </div>
                        <div class="col-md-8 d-flex justify-content-end">
                            <a asp-action="Create" asp-controller="ChecklistItems" class="btn btn-primary">New Checklist Item</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Title</th>
                                <th scope="col">Desciprion</th>
                                <th scope="col">Due At</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.ChecklistItems != null)
                            {
                                @foreach (ChecklistItem item in Model.ChecklistItems)
                                {
                                    @if (!item.IsDone) 
                                    {
                                        <tr>
                                            <td>@item.Title</td>
                                            <td>@item.Description</td>
                                            <td>@item.DateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</td>
                                            <td>
                                                <form method="post" asp-action="MarkAsDone" asp-controller="Client">
                                                    <input type="hidden" name="itemId" value="@item.Id" />
                                                    <button type="submit" class="btn btn-sm btn-outline-success">✅ Mark Done</button>
                                                </form>
                                            </td>
                                        </tr>
                                    }
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4" class="text-center">No ToDo items found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card table-card mt-5">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-4">
                            <h3>Wedding Timeline</h3>
                        </div>
                        <div class="col-md-8 d-flex justify-content-end">
                            <a asp-action="Create" asp-controller="Timelines" class="btn btn-primary">Add New Timeline</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Title</th>
                                <th scope="col">Start Time</th>
                                <th scope="col">End Time</th>
                                <th scope="col">Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Timelines != null)
                            {
                                @foreach (Timeline item in Model.Timelines)
                                {
                                    <tr>
                                        <td>@item.Title</td>
                                        <td>@item.StartTime.ToString("MM/dd/yyyy hh:mm:ss tt")</td>
                                        <td>@item.EndTime.ToString("MM/dd/yyyy hh:mm:ss tt")</td>
                                        <td>
                                            @if (item.IsDone)
                                            {
                                                <span class="badge rounded-pill text-bg-success p-2">Completed</span>
                                            }
                                            else
                                            {
                                                <span class="badge rounded-pill text-bg-warning p-2">Not Completed</span>
                                            }
                                        </td>
                                        <td>
                                            @if (!item.IsDone)
                                            {
                                                <form method="post" asp-action="MarkRimelineAsDone" asp-controller="Client">
                                                    <input type="hidden" name="itemId" value="@item.Id" />
                                                    <button type="submit" class="btn btn-sm btn-outline-success">✅ Mark Done</button>
                                                </form>
                                            }
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4" class="text-center">No Timeline items found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card table-card">
                <div class="card-header">
                    <h3>Wedding Details</h3>
                </div>
                <div class="card-body">
                    @if (Model != null && Model.ChecklistItems != null)
                    {
                        <ul class="list-group">
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h5 class="mb-0">Wedding Date</h5>
                                    </div>
                                    <div class="col-md-9">
                                        <p class="mb-0">@Model.WeddingDate.ToString("MM/dd/yyyy")</p>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h5 class="mb-0">Wedding Planner</h5>
                                    </div>
                                    <div class="col-md-9">
                                        @if (Model.Planner != null)
                                        {
                                            <div class="d-flex gap-2">
                                                <p class="mb-1">@Model.Planner?.FirstName @Model.Planner?.LastName</p> |
                                                <p class="mb-1">@Model.Planner?.Email</p> |
                                                <p class="mb-1">@Model.Planner?.PhoneNumber</p>
                                            </div>
                                        } else {
                                            <div class="d-flex gap-3">
                                                <p class="mb-0">Select a planner for your wedding</p>
                                                <a asp-action="SelectPlanner" asp-controller="Weddings" class="btn btn-primary btn-sm" style="height: fit-content;">Select</a>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h5 class="mb-0">Total Guest Count</h5>
                                    </div>
                                    <div class="col-md-9">
                                        <p class="mb-0">@Model.TotalGuests</p>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h5 class="mb-0">Full Budget</h5>
                                    </div>
                                    <div class="col-md-9">
                                        <p class="mb-0">Rs @Model.FullBudget</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <p>Weding is not setup yet</p>
                        <p>Click the button below to setup your wedding</p>
                        <a asp-action="Create" asp-controller="Weddings" class="btn btn-primary">Setup Wedding</a>
                    }
                </div>
            </div>
            <div class="card table-card mt-5">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-4">
                            <h3>Wedding Guest List</h3>
                        </div>
                        <div class="col-md-8 d-flex justify-content-end">
                            <a asp-action="Create" asp-controller="Guests" class="btn btn-primary">Add New Guest</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Full Name</th>
                                <th scope="col">Phone Number</th>
                                <th scope="col">Meal Preference</th>
                                <th scope="col">Table Number</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Guests != null)
                            {
                                @foreach (Guest item in Model.Guests)
                                {
                                    @if (!item.RSVP)
                                    {
                                        <tr>
                                            <td>@item.FullName</td>
                                            <td>@item.Phone</td>
                                            <td>@item.MealPreference</td>
                                            <td>@item.TableNumber</td>
                                            <td>
                                                <form method="post" asp-action="MarkAsAttending" asp-controller="Client">
                                                    <input type="hidden" name="itemId" value="@item.Id" />
                                                    <button type="submit" class="btn btn-sm btn-outline-success">✅ Mark Attend</button>
                                                </form>
                                            </td>
                                        </tr>
                                    }
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4" class="text-center">No Guest found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>